### ISSUE TITLE
Error in loading export react-icons/all

### ISSUE THREAD

**Issue by aadi-rajat** [jim-junior/reactjs-media#259]
Hi, 

I am gettting the below error while building project. 

![image](https://github.com/jim-junior/reactjs-media/assets/8972768/64e67163-e8a9-409f-9e4f-734e3951f186)

using 

"reactjs-media": "^2.2.0" version from the NPM

Dependencies

![image](https://github.com/jim-junior/reactjs-media/assets/8972768/9651e9eb-70f4-48b1-b921-0406a01081a3)

**Comment by xorozo** [comment]
The same error
