### ISSUE TITLE
React icons library breaking performance

### ISSUE THREAD

**Issue by Baivaras** [jim-junior/reactjs-media#83]
Hello,

I am using reactjs-media V1.5.1 inside my Gatsby project and realized that react-icons take a lot of space inside the project as the entire `react-icons/md` library is imported. And the newest version of the package is importing `react-icons/all` which adds an extra 20-25 MB to the built project.

For the users like me, I suggest you change the `react-icons` package to `@react-icons/all-files` and then import required icons one by one like this `import { FaBeer } from "@react-icons/all-files/fa/FaBeer";`

Thanks

**Comment by jim-junior** [comment]
The issue has been solved in `v2.2.0` the package only imports the required components as you recommended.
