### ISSUE TITLE
error and confilict

### ISSUE THREAD

**Issue by fkazemi5236** [jim-junior/reactjs-media#84]
i just use this package in my app and show me this error 
<img width="909" alt="Screen Shot 1400-09-29 at 02 50 57" src="https://user-images.githubusercontent.com/46262018/146694663-960d0fe8-0800-40da-9abb-c861991acd60.png">

**Comment by jim-junior** [comment]
What version are you using??

I recommend updating to the latest version because that error seems to have been fixed already.

**Comment by fkazemi5236** [comment]
i am using the latest version on "react": "17.0.2",  "react-native": "^0.66.3",

**Comment by jim-junior** [comment]
Try using reactjs-media version 2.2.0

**Comment by onlykingKD** [comment]
> i am using the latest version on "react": "17.0.2", "react-native": "^0.66.3",

downgrade create-react-webpack to version 4

**Comment by mubeenullhaq** [comment]
I am facing the same issue. I am using "reactjs-media":"^2.2.0" and
 "react": "^17.0.2". 
I have tried downgrading to "react": "^16.0.3" but I got no success.
Please guide me how can I tackle this error.

**Comment by onlykingKD** [comment]
> I am facing the same issue. I am using "reactjs-media":"^2.2.0" and "react": "^17.0.2". I have tried downgrading to "react": "^16.0.3" but I got no success. Please guide me how can I tackle this error.

try this :
```
npm uninstall webpack
npm install webpack@4.0.3
```

**Comment by Kathalysth** [comment]
is there another solution to this issue that will not involve downgrading my webpack?
