### ISSUE TITLE
SyntaxError: Unexpected token 'export' 

### ISSUE THREAD

**Issue by chrispter** [jim-junior/reactjs-media#92]
I want to use reactjs-media but have this problem when I want to export it

Could not find a declaration file for module 'reactjs-media'. '../node_modules/reactjs-media/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/reactjs-media` if it exists or add a new declaration (.d.ts) file containing `declare module 'reactjs-media';`ts(7016)

**Comment by jim-junior** [comment]
Fixed in v3.0.1
